services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama_models:/root/.ollama
    networks:
      - app-network
    # Optional: Use a larger CPU/memory if available
    mem_limit: 8g
    restart: unless-stopped

networks:
  app-network:
    driver: bridge